version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: karavan
   # environment:
    #  - MONGO_URI=mongodb://mogo:27017
    ports:
      - 80:3010
    networks:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - 27017
    networks:
      - backend

networks:
  backend:
